In [1]:
list1 = [10, 20, 30, 40, 50]
list2 = [1, 2, 3, 4, 5]

#元素的數量
display(list1 + list2)

display(list1 * 2)

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [2]:
#陣列運算
import numpy as np
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([1, 2, 3, 4, 5])

#陣列運算
display(array1 + array2)

display(array1 * 2)

array([11, 22, 33, 44, 55])

array([ 20,  40,  60,  80, 100])

In [3]:
(4)
(4,)

(4,)

In [4]:
#ndarray的形狀
array1.shape

(5,)

In [5]:
#使用內建的function建立ndarray
np.linspace(2.0, 3.0, num=100)

array([2.        , 2.01010101, 2.02020202, 2.03030303, 2.04040404,
       2.05050505, 2.06060606, 2.07070707, 2.08080808, 2.09090909,
       2.1010101 , 2.11111111, 2.12121212, 2.13131313, 2.14141414,
       2.15151515, 2.16161616, 2.17171717, 2.18181818, 2.19191919,
       2.2020202 , 2.21212121, 2.22222222, 2.23232323, 2.24242424,
       2.25252525, 2.26262626, 2.27272727, 2.28282828, 2.29292929,
       2.3030303 , 2.31313131, 2.32323232, 2.33333333, 2.34343434,
       2.35353535, 2.36363636, 2.37373737, 2.38383838, 2.39393939,
       2.4040404 , 2.41414141, 2.42424242, 2.43434343, 2.44444444,
       2.45454545, 2.46464646, 2.47474747, 2.48484848, 2.49494949,
       2.50505051, 2.51515152, 2.52525253, 2.53535354, 2.54545455,
       2.55555556, 2.56565657, 2.57575758, 2.58585859, 2.5959596 ,
       2.60606061, 2.61616162, 2.62626263, 2.63636364, 2.64646465,
       2.65656566, 2.66666667, 2.67676768, 2.68686869, 2.6969697 ,
       2.70707071, 2.71717172, 2.72727273, 2.73737374, 2.74747